site_name: nimbus
theme:
  name: material
  logo: logo/large.svg
  favicon: logo/favicon.svg
  features:
    - content.code.copy
    - content.code.annotate
    - search.highlight
    - search.suggest
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to auto mode
plugins:
  - search
  - markdown-exec
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            inherited_members: true
            separate_signature: true
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true

            show_root_heading: true
            show_root_full_path: false
            heading_level: 3
            unwrap_annotated: true
            extensions:
              - griffe_pydantic:
                  schema: true
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - admonition
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - toc:
      permalink: "¤"


nav:
- Getting Started: index.md
- Commands:
  - Data:
    - version: version.md
    - devdetails: devdetails.md
    - pools: pools.md
    - summary: summary.md
    - hardware: hardware.md
    - network: network.md
  - Control:
    - reboot: reboot.md
    - restart: restart.md
    - pause: pause.md
    - resume: resume.md
    - setpools: setpools.md
  - Common: common.md
- Optional Commands:
  - Tuning:
    - setpower: extensions/tuning/setpower.md
    - sethashrate: extensions/tuning/sethashrate.md
- Push Model:
  - Getting Started: push/index.md
  - Data: push/data.md
watch:
  - nimbus/
extra_css:
  - stylesheets/admonitions.css
