site_name: nimbus
theme:
  name: material
  logo: logo/large.svg
  favicon: logo/favicon.svg
  features:
    - content.code.copy
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to auto mode
plugins:
  - search
  - markdown-exec
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_root_heading: true
            show_root_full_path: false
            heading_level: 3
            unwrap_annotated: true
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition


nav:
- Commands:
  - Common: index.md
  - Data:
    - CGMiner Compatible:
      - version: version.md
      - devdetails: devdetails.md
      - pools: pools.md
    - Partially CGMiner Compatible:
      - summary: summary.md
    - Nimbus Commands:
      - hardware: hardware.md
      - network: network.md
  - Control:
    - Nimbus Commands:
      - reboot: reboot.md
watch:
  - nimbus/
extra_css:
  - stylesheets/admonitions.css
